// Markdown + KaTeX 渲染（唯一 v-html 入口必须经 DOMPurify）。
// XSS 防线：禁脚本/事件/危险标签；允许 KaTeX 的 MathML 命名空间标签，
// 但其它命名空间（SVG 等）一律不放行。

import { marked } from "marked";
import DOMPurify from "dompurify";
import katex from "katex";
import "katex/dist/katex.min.css";
// mhchem 扩展：注册 \ce{} / \pu{} 等化学宏（化学式、方程式、同位素、单位）。
import "katex/dist/contrib/mhchem.mjs";
import markedKatex from "marked-katex-extension";

marked.use(
  markedKatex({
    throwOnError: false,
    output: "htmlAndMathml",
    // 允许中文等非空格字符紧贴 $ 前的公式（如"化学式：$H_2O$"）。
    nonStandard: true,
  }),
);

const MATH_TAGS = [
  "math",
  "annotation",
  "annotation-xml",
  "menclose",
  "merror",
  "mfenced",
  "mfrac",
  "mi",
  "mmultiscripts",
  "mn",
  "mo",
  "mover",
  "mpadded",
  "mphantom",
  "mprescripts",
  "mroot",
  "mrow",
  "ms",
  "mspace",
  "msqrt",
  "mstyle",
  "msub",
  "msubsup",
  "msup",
  "mtable",
  "mtd",
  "mtext",
  "mtr",
  "munder",
  "munderover",
  "none",
];

const MATH_ATTRS = [
  "xmlns",
  "accent",
  "accentunder",
  "align",
  "bevelled",
  "close",
  "columnlines",
  "columnspacing",
  "columnspan",
  "denomalign",
  "depth",
  "dir",
  "displaystyle",
  "fence",
  "form",
  "frame",
  "framespacing",
  "height",
  "linethickness",
  "lspace",
  "lquote",
  "mathbackground",
  "mathcolor",
  "mathsize",
  "mathvariant",
  "maxsize",
  "minsize",
  "movablelimits",
  "notation",
  "numalign",
  "open",
  "rowalign",
  "rowlines",
  "rowspacing",
  "rowspan",
  "rspace",
  "rquote",
  "scriptlevel",
  "scriptminsize",
  "scriptsizemultiplier",
  "selection",
  "separator",
  "separators",
  "stretchy",
  "subscriptshift",
  "superscriptshift",
  "symmetric",
  "voffset",
  "width",
  "xlink:href",
  "xlink:show",
  "xlink:type",
  "xmlns:xlink",
];

const FORBID_ATTR = [
  "onerror",
  "onload",
  "onclick",
  "ondblclick",
  "onmouseover",
  "onmouseout",
  "onmousedown",
  "onmouseup",
  "onmousemove",
  "onmouseenter",
  "onmouseleave",
  "onfocus",
  "onblur",
  "onchange",
  "oninput",
  "onkeydown",
  "onkeyup",
  "onkeypress",
  "onsubmit",
  "onreset",
  "oncontextmenu",
  "onauxclick",
  "onpointerdown",
  "onpointerup",
  "onpointerenter",
  "onpointerleave",
  "onpointermove",
  "ondrag",
  "ondrop",
  "onpaste",
  "oncopy",
  "oncut",
];

export function renderMarkdown(text) {
  const html = marked.parse(text ?? "", { async: false });
  return DOMPurify.sanitize(html, {
    USE_PROFILES: { html: true, mathMl: true, svg: false },
    ADD_TAGS: MATH_TAGS,
    ADD_ATTR: MATH_ATTRS,
    FORBID_TAGS: [
      "script",
      "style",
      "iframe",
      "object",
      "embed",
      "form",
      "input",
      "textarea",
      "button",
      "select",
      "option",
      "svg",
    ],
    FORBID_ATTR,
  });
}
